### ISSUE TITLE
Doesn't build in VS 2019 with latest preview of project reunion installed.

### ISSUE THREAD

**Issue by aqibbanday** [jtbrower/WinUI#1]

**Comment by jtbrower** [comment]
Hello, back in July of 2021 when you reported this issue, the project's main readme had already been updated to indicate why development had stopped, but I had yet to archive the repository as I should have. Per Microsoft's recommendations, I am closing this out and then archiving the repository.  Since it has been two years since you reported this, I know it is likely the least of your concerns.
